version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: ms-sql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=<YourStrong@Passw0rd>
    ports:
      - "1433:1433"
    volumes:
      - ~/docker/mssql:/VAR/OPT/MSSQLHOST
